[package]
org = "samples"
name = "expense_approval"
version = "0.1.0"
distribution = "2201.14.0"

[build-options]
observabilityIncluded = false

[[dependency]]
org = "hasitha"
name = "workflow.runtime.bridge"
version = "0.1.0"
repository = "local"
